AllCops:
  TargetRubyVersion: 3.0

Layout/EmptyLines:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/ClassAndModuleCamelCase:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GlobalVars:
  Enabled: false
